### ISSUE TITLE
Remixer window defaults to tiny size

### ISSUE THREAD

**Issue by ironminer888** [chrislo27/RhythmHeavenRemixer#1]
Perhaps it's because I set my appLocale to Japanese that one time? https://i.redd.it/hy8wxvm9ixox.png

**Comment by chrislo27** [comment]
Go to `<user>/.prefs/RhythmHeavenRemixBoard-settings`, open it in Notepad++, check the actualWidth and actualHeight settings. Change it back to 1280 and 720. Report back if it works or not.
